services:
  {{cookiecutter.project_slug}}-server:
    container_name: {{cookiecutter.project_slug}}-server
    image: nginx:stable-bullseye
    restart: always
    networks:
      - {{cookiecutter.project_slug}}_network
    ports:
      - "{{cookiecutter.open_port}}:{{cookiecutter.open_port}}"
    volumes:
      - ./dockerization/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./dockerization/nginx/site.conf:/etc/nginx/conf.d/site.conf:ro
      - static-data:/static
    depends_on:
      - {{cookiecutter.project_slug}}-app

  {{cookiecutter.project_slug}}-app:
    container_name: {{cookiecutter.project_slug}}-app
    restart: always
    build:
      context: ./
      dockerfile: dockerization/Dockerfile
    networks:
      - {{cookiecutter.project_slug}}_network
    expose:
      - 8055
    volumes:
      - static-data:/static
    command: sh -c "python manage.py migrate && gunicorn wsgi --bind 0.0.0.0:8055 --error-logfile /var/log/gunicorn/error.log --access-logfile /var/log/gunicorn/access.log"
    env_file:
      - .env

  {{cookiecutter.project_slug}}-bot:
    container_name: {{cookiecutter.project_slug}}-bot
    hostname: {{cookiecutter.project_slug}}-bot
    restart: always
    build:
      context: ./
      dockerfile: dockerization/Dockerfile
    networks:
      - {{cookiecutter.project_slug}}_network
    command: python manage.py start_polling
    env_file:
      - .env

networks:
  {{cookiecutter.project_slug}}_network:
    name: {{cookiecutter.project_slug}}_network

volumes:
  static-data:
